
services:
  bookify.api:
    image: bookifyapi
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    depends_on:
      - bookify-db
  bookify-db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: Bookify.Db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1234512345Aa$
      - MSSQL_PID=Express
    volumes:
      - ./.containers/database:/var/opt/mssql/data
    ports:
      - "1433:1433"
